theme: jekyll-theme-cayman
title: PoseCVAE - Anomalous Human Activity Detection
description: Indian Institute of Technology Bombay
github:
 repository_url: https://github.com/Ashvini-Kumar-Sharma/PoseCVAE/blob/main/README.md
 arxiv: https://github.com/Ashvini-Kumar-Sharma/PoseCVAE/blob/main/README.md
